robot:
  name: beemoAI

router:
  host: localhost
  port: 5555

components:
  # example:
  #   file: components/example.py
  #   channels:
  #     /s/example/data: write

  pi_camera:
    file: components/pi_camera.py
    groups: [camera]
    requires:
      - rpicam-hello
    channels:
      /s/camera/frame: write

  stream_display:
    file: components/stream_display.py
    groups: [camera]
    channels:
      /s/camera/frame: read

  motor_driver:
    file: components/motor_driver.py
    groups: [drive, dashboard]
    channels:
      /c/motor/drive: read

  keyboard_control:
    file: components/keyboard_control.py
    groups: [drive]
    channels:
      /c/motor/drive: write

  screen_display:
    file: components/screen_display.py
    groups: [screen, dashboard]
    channels:
      /s/screen/display: read

  beemo_face:
    file: components/beemo_face.py
    groups: [screen, dashboard]
    channels:
      /s/screen/display: write

  usb_microphone:
    file: components/usb_microphone.py
    groups: [audio, dashboard]
    channels:
      /s/microphone/audio: write

  audio_visualizer:
    file: components/audio_visualizer.py
    groups: [audio]
    channels:
      /s/microphone/audio: read

  speaker:
    file: components/speaker.py
    groups: [speaker, dashboard]
    channels:
      /s/speaker/audio: read

  test_speaker:
    file: components/test_speaker.py
    groups: [speaker]
    channels:
      /s/speaker/audio: write

  button_matrix:
    file: components/button_matrix.py
    groups: [buttons, dashboard]
    channels:
      /s/buttons/event: write

  button_reader:
    file: components/button_reader.py
    groups: [buttons]
    channels:
      /s/buttons/event: read

  main:
    file: components/main.py
    groups: [dashboard]
    channels:
      /s/camera/frame: read
      /s/screen/display: readwrite
      /s/microphone/audio: read
      /s/speaker/audio: readwrite
      /c/motor/drive: readwrite
      /s/buttons/event: read
